# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/cisco.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12protos/cisco.proto\x12\ncisco_grpc\"(\n\nConfigArgs\x12\r\n\x05reqID\x18\x01 \x01(\t\x12\x0b\n\x03\x63li\x18\x02 \x01(\t\"<\n\x0b\x43onfigReply\x12\r\n\x05reqID\x18\x01 \x01(\t\x12\x0e\n\x06output\x18\x02 \x01(\t\x12\x0e\n\x06\x65rrors\x18\x03 \x01(\t2K\n\x0egRPCConfigOper\x12\x39\n\x06\x43onfig\x12\x16.cisco_grpc.ConfigArgs\x1a\x17.cisco_grpc.ConfigReplyb\x06proto3')



_CONFIGARGS = DESCRIPTOR.message_types_by_name['ConfigArgs']
_CONFIGREPLY = DESCRIPTOR.message_types_by_name['ConfigReply']
ConfigArgs = _reflection.GeneratedProtocolMessageType('ConfigArgs', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGARGS,
  '__module__' : 'protos.cisco_pb2'
  # @@protoc_insertion_point(class_scope:cisco_grpc.ConfigArgs)
  })
_sym_db.RegisterMessage(ConfigArgs)

ConfigReply = _reflection.GeneratedProtocolMessageType('ConfigReply', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGREPLY,
  '__module__' : 'protos.cisco_pb2'
  # @@protoc_insertion_point(class_scope:cisco_grpc.ConfigReply)
  })
_sym_db.RegisterMessage(ConfigReply)

_GRPCCONFIGOPER = DESCRIPTOR.services_by_name['gRPCConfigOper']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONFIGARGS._serialized_start=34
  _CONFIGARGS._serialized_end=74
  _CONFIGREPLY._serialized_start=76
  _CONFIGREPLY._serialized_end=136
  _GRPCCONFIGOPER._serialized_start=138
  _GRPCCONFIGOPER._serialized_end=213
# @@protoc_insertion_point(module_scope)
