# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import cisco_pb2 as protos_dot_cisco__pb2


class gRPCConfigOperStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Config = channel.unary_unary(
                '/cisco_grpc.gRPCConfigOper/Config',
                request_serializer=protos_dot_cisco__pb2.ConfigArgs.SerializeToString,
                response_deserializer=protos_dot_cisco__pb2.ConfigReply.FromString,
                )


class gRPCConfigOperServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Config(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_gRPCConfigOperServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Config': grpc.unary_unary_rpc_method_handler(
                    servicer.Config,
                    request_deserializer=protos_dot_cisco__pb2.ConfigArgs.FromString,
                    response_serializer=protos_dot_cisco__pb2.ConfigReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cisco_grpc.gRPCConfigOper', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class gRPCConfigOper(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Config(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cisco_grpc.gRPCConfigOper/Config',
            protos_dot_cisco__pb2.ConfigArgs.SerializeToString,
            protos_dot_cisco__pb2.ConfigReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
