# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import network_manager_pb2 as protos_dot_network__manager__pb2


class NetworkManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConfigureInterfaces = channel.unary_unary(
                '/network_manager.NetworkManager/ConfigureInterfaces',
                request_serializer=protos_dot_network__manager__pb2.InterfaceConfigRequest.SerializeToString,
                response_deserializer=protos_dot_network__manager__pb2.ConfigResponse.FromString,
                )
        self.GetTelemetry = channel.unary_stream(
                '/network_manager.NetworkManager/GetTelemetry',
                request_serializer=protos_dot_network__manager__pb2.TelemetryRequest.SerializeToString,
                response_deserializer=protos_dot_network__manager__pb2.TelemetryData.FromString,
                )


class NetworkManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ConfigureInterfaces(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTelemetry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NetworkManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConfigureInterfaces': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureInterfaces,
                    request_deserializer=protos_dot_network__manager__pb2.InterfaceConfigRequest.FromString,
                    response_serializer=protos_dot_network__manager__pb2.ConfigResponse.SerializeToString,
            ),
            'GetTelemetry': grpc.unary_stream_rpc_method_handler(
                    servicer.GetTelemetry,
                    request_deserializer=protos_dot_network__manager__pb2.TelemetryRequest.FromString,
                    response_serializer=protos_dot_network__manager__pb2.TelemetryData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'network_manager.NetworkManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NetworkManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConfigureInterfaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/network_manager.NetworkManager/ConfigureInterfaces',
            protos_dot_network__manager__pb2.InterfaceConfigRequest.SerializeToString,
            protos_dot_network__manager__pb2.ConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/network_manager.NetworkManager/GetTelemetry',
            protos_dot_network__manager__pb2.TelemetryRequest.SerializeToString,
            protos_dot_network__manager__pb2.TelemetryData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
