# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/network_manager.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cprotos/network_manager.proto\x12\x0fnetwork_manager\"Y\n\x0fInterfaceConfig\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x12\n\nip_address\x18\x03 \x01(\t\x12\x0f\n\x07\x65nabled\x18\x04 \x01(\x08\"N\n\x16InterfaceConfigRequest\x12\x34\n\ninterfaces\x18\x01 \x03(\x0b\x32 .network_manager.InterfaceConfig\"2\n\x0e\x43onfigResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\'\n\x10TelemetryRequest\x12\x13\n\x0bsensor_path\x18\x01 \x01(\t\"\x8c\x01\n\rTelemetryData\x12\x13\n\x0bsensor_path\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t\x12\x0b\n\x03key\x18\x03 \x01(\t\x12\x14\n\ndouble_val\x18\x04 \x01(\x01H\x00\x12\x11\n\x07int_val\x18\x05 \x01(\x03H\x00\x12\x14\n\nstring_val\x18\x06 \x01(\tH\x00\x42\x07\n\x05value2\xc6\x01\n\x0eNetworkManager\x12_\n\x13\x43onfigureInterfaces\x12\'.network_manager.InterfaceConfigRequest\x1a\x1f.network_manager.ConfigResponse\x12S\n\x0cGetTelemetry\x12!.network_manager.TelemetryRequest\x1a\x1e.network_manager.TelemetryData0\x01\x62\x06proto3')



_INTERFACECONFIG = DESCRIPTOR.message_types_by_name['InterfaceConfig']
_INTERFACECONFIGREQUEST = DESCRIPTOR.message_types_by_name['InterfaceConfigRequest']
_CONFIGRESPONSE = DESCRIPTOR.message_types_by_name['ConfigResponse']
_TELEMETRYREQUEST = DESCRIPTOR.message_types_by_name['TelemetryRequest']
_TELEMETRYDATA = DESCRIPTOR.message_types_by_name['TelemetryData']
InterfaceConfig = _reflection.GeneratedProtocolMessageType('InterfaceConfig', (_message.Message,), {
  'DESCRIPTOR' : _INTERFACECONFIG,
  '__module__' : 'protos.network_manager_pb2'
  # @@protoc_insertion_point(class_scope:network_manager.InterfaceConfig)
  })
_sym_db.RegisterMessage(InterfaceConfig)

InterfaceConfigRequest = _reflection.GeneratedProtocolMessageType('InterfaceConfigRequest', (_message.Message,), {
  'DESCRIPTOR' : _INTERFACECONFIGREQUEST,
  '__module__' : 'protos.network_manager_pb2'
  # @@protoc_insertion_point(class_scope:network_manager.InterfaceConfigRequest)
  })
_sym_db.RegisterMessage(InterfaceConfigRequest)

ConfigResponse = _reflection.GeneratedProtocolMessageType('ConfigResponse', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGRESPONSE,
  '__module__' : 'protos.network_manager_pb2'
  # @@protoc_insertion_point(class_scope:network_manager.ConfigResponse)
  })
_sym_db.RegisterMessage(ConfigResponse)

TelemetryRequest = _reflection.GeneratedProtocolMessageType('TelemetryRequest', (_message.Message,), {
  'DESCRIPTOR' : _TELEMETRYREQUEST,
  '__module__' : 'protos.network_manager_pb2'
  # @@protoc_insertion_point(class_scope:network_manager.TelemetryRequest)
  })
_sym_db.RegisterMessage(TelemetryRequest)

TelemetryData = _reflection.GeneratedProtocolMessageType('TelemetryData', (_message.Message,), {
  'DESCRIPTOR' : _TELEMETRYDATA,
  '__module__' : 'protos.network_manager_pb2'
  # @@protoc_insertion_point(class_scope:network_manager.TelemetryData)
  })
_sym_db.RegisterMessage(TelemetryData)

_NETWORKMANAGER = DESCRIPTOR.services_by_name['NetworkManager']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INTERFACECONFIG._serialized_start=49
  _INTERFACECONFIG._serialized_end=138
  _INTERFACECONFIGREQUEST._serialized_start=140
  _INTERFACECONFIGREQUEST._serialized_end=218
  _CONFIGRESPONSE._serialized_start=220
  _CONFIGRESPONSE._serialized_end=270
  _TELEMETRYREQUEST._serialized_start=272
  _TELEMETRYREQUEST._serialized_end=311
  _TELEMETRYDATA._serialized_start=314
  _TELEMETRYDATA._serialized_end=454
  _NETWORKMANAGER._serialized_start=457
  _NETWORKMANAGER._serialized_end=655
# @@protoc_insertion_point(module_scope)
